# Generated by Django 4.2 on 2023-04-24 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                (
                    "article_number",
                    models.PositiveBigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "measurement",
                    models.CharField(
                        choices=[
                            ("pc", "Piece"),
                            ("g", "gram"),
                            ("kg", "kilogram"),
                            ("lb", "Pound"),
                            ("oz", "Ounce"),
                            ("ml", "Milliliter"),
                            ("l", "Liter"),
                            ("fl. oz", "Fluid Ounce"),
                            ("gal", "Gallon"),
                            ("in", "Inch"),
                            ("ft", "Foot"),
                            ("yd", "Yard"),
                            ("mi", "Mile"),
                            ("cm", "Centimeter"),
                            ("m", "Meter"),
                            ("km", "Kilometer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient",
                        to="recipes.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "measurement",
                    models.CharField(
                        choices=[
                            ("pc", "Piece"),
                            ("g", "gram"),
                            ("kg", "kilogram"),
                            ("lb", "Pound"),
                            ("oz", "Ounce"),
                            ("ml", "Milliliter"),
                            ("l", "Liter"),
                            ("fl. oz", "Fluid Ounce"),
                            ("gal", "Gallon"),
                            ("in", "Inch"),
                            ("ft", "Foot"),
                            ("yd", "Yard"),
                            ("mi", "Mile"),
                            ("cm", "Centimeter"),
                            ("m", "Meter"),
                            ("km", "Kilometer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredient",
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="productprice",
            name="product",
        ),
        migrations.RemoveField(
            model_name="recipeproduct",
            name="product",
        ),
        migrations.RemoveField(
            model_name="recipeproduct",
            name="recipe",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductPrice",
        ),
        migrations.DeleteModel(
            name="RecipeProduct",
        ),
    ]
