# Generated by Django 4.2 on 2023-04-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_ingredient_ingredientprice_recipeingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("pc", "Piece"),
                    ("g", "gram"),
                    ("kg", "kilogram"),
                    ("lb", "Pound"),
                    ("oz", "Ounce"),
                    ("cl", "Centiliter"),
                    ("ml", "Milliliter"),
                    ("l", "Liter"),
                    ("fl. oz", "Fluid Ounce"),
                    ("gal", "Gallon"),
                    ("in", "Inch"),
                    ("ft", "Foot"),
                    ("yd", "Yard"),
                    ("mi", "Mile"),
                    ("cm", "Centimeter"),
                    ("m", "Meter"),
                    ("km", "Kilometer"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("pc", "Piece"),
                    ("g", "gram"),
                    ("kg", "kilogram"),
                    ("lb", "Pound"),
                    ("oz", "Ounce"),
                    ("cl", "Centiliter"),
                    ("ml", "Milliliter"),
                    ("l", "Liter"),
                    ("fl. oz", "Fluid Ounce"),
                    ("gal", "Gallon"),
                    ("in", "Inch"),
                    ("ft", "Foot"),
                    ("yd", "Yard"),
                    ("mi", "Mile"),
                    ("cm", "Centimeter"),
                    ("m", "Meter"),
                    ("km", "Kilometer"),
                ],
                max_length=10,
            ),
        ),
    ]
